version: '2.1'
orbs:
  node: circleci/node@5.0.3
jobs:
  test:
    executor:
      name: node/default
      tag: '18.13.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm test
workflows:
  test_my_app:
    jobs:
      - test
